name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Release
        run: |
          git config --global user.name 'Release Workflow'
          git config --global user.email '${{ github.triggering_actor }}@users.noreply.github.com'
          fullrelease --no-input
