name: Create a release

on:
  workflow_dispatch:
    inputs:
      target_version:
        required: true
        type: string
        description: Target release version

env:
  # renovate: datasource=pypi depName=poetry
  POETRY_VERSION: 2.2.1

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Run release
        run: poetry run release ${{ inputs.target_version }}