name: Create a release

on:
  workflow_dispatch:
    inputs:
      target_version:
        required: true
        type: string
        description: Target release version

env:
  # renovate: datasource=pypi depName=poetry
  POETRY_VERSION: 1.8.5

jobs:
  release:
    if: ${{ inputs.target_version }}

    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Run release
        run: poetry run release ${{ inputs.target_version }}