name: Python validation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8 cleaner --show-source --statistics
      - name: mypy
        run: mypy cleaner
      - name: Pytest
        run: pytest tests